# Generated by Django 4.2.7 on 2023-11-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contentTwo',
        ),
    ]
